version: 2

models:
  - name: dim_listings_cleansed
    description: "This model contains the Airbnb listings dim_listings_cleansed data."
    columns:
      - name: listing_id
        description: "Unique identifier for each listing."
        tests:
          - not_null
          - unique    
      - name: host_id
        description: "Unique identifier for the host of the listing."
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id
      - name: room_type
        description: "Name of the host for the listing."
        tests:
          - not_null
          - accepted_values:
              values: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']

