version: 2

sources:
  - name: airbnb
    schema: raw
    tables:
      - name: listings
        identifier: raw_listings

      - name: hosts
        identifier: raw_hosts

      - name: reviews
        identifier: raw_reviews
        loaded_at_field: date
        freshness:
          error_after: {count: 30, period: hour}
          warn_after: {count: 1, period: hour}


# So if it won't find any data that's less than one hour fresh, then it will give us a warning.
# And if it won't find any data in the past 24 hours, then it will give us an error.